export const FCM_INVALID_ARGUMENT_ERROR_CODE = 'messaging/invalid-argument';
export const FCM_UNREGISTERED_ERROR_CODE =
  'messaging/registration-token-not-registered';
export const MAX_RETRIES_QUEUE = 4;
export const RETRY_DELAY = 5000;
export const OBJECT_ID_PATTERN = /^[0-9a-fA-F]{24}$/;
export const PIN_CODE_PATTERN = /^\d{4}$/;
export const LIMIT_FREE = {
  FOLDER: 1,
  NOTE: 3,
  DIARY: 3,
};

export const ERROR_CODE = {
  MUST_UPGRADE_TO_PREMIUM: 'MUST_UPGRADE_TO_PREMIUM',
  TRY_AGAIN_IN_30_MINUTES: 'TRY_AGAIN_IN_30_MINUTES',
  TOO_MANY_ATTEMPTS_TRY_LATER: 'TOO_MANY_ATTEMPTS_TRY_LATER',
  REQUEST_NEW_OTP_LATER: 'REQUEST_NEW_OTP_LATER',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  TRY_AGAIN_IN_10_MINUTES: 'TRY_AGAIN_IN_10_MINUTES',
  BLOCK_IN_10_MINUTES: 'BLOCK_IN_10_MINUTES',
  OTP_NOT_MATCH: 'OTP_NOT_MATCH',
  INVALID_FILE_UPLOAD: 'INVALID_FILE_UPLOAD',
};
export const MAX_SIZE_UPLOAD_IMAGE_APP = 100 * 1024 * 1024; // 100mb
export const MAX_FILES_UPLOAD = 5;
export const LIMIT_DAYS_IN_TRASH = 30;
