name: CD for Chefly API

on:
  pull_request:
    types: [closed] # Trigger when a PR is closed (merged or not)
    branches:
      - main

env:
  NODE_VERSION: '18.x'
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' # Only deploy if PR is merged into main
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 5: Pull Vercel environment variables
      - name: Pull Vercel Environment
        run: vercel pull --yes --environment production --token ${{ secrets.VERCEL_TOKEN }}

      # Step 6: Build the project for Vercel
      - name: Build Project
        run: npm run vercel-build
        env:
          VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}

      # Step 7: Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}